apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: special-resource-operator
  namespace: openshift-special-resource-operator
spec:
  channel: "4.9"
  installPlanApproval: Automatic
  name: special-resource-operator
  source: qe-app-registry
  #source: redhat-operators
  sourceNamespace: openshift-marketplace
