ocp_channel=`oc get packagemanifest performance-addon-operator -n openshift-marketplace -o jsonpath='{.status.defaultChannel}'`
oc create -f- <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
spec:
  channel: "$ocp_channel" 
  name: performance-addon-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
