apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example
  annoations:
    #Only disable CPU load balancing when the CPU manager static policy is enabled and for pods with guaranteed QoS that use whole CPUs. Otherwise, disabling CPU load balancing can affect the performance of other containers in the cluster.
    cpu-load-balancing.crio.io: true
spec:
  containers:
  - name: qos-demo-ctr
    image: quay.io/openshift-psap-qe/linuxperformance:latest
    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
      requests:
        memory: "200Mi"
        cpu: "1"
    runtimeClassName: performance-<profile_name>
    nodeSelector:
      node-role.kubernetes.io/worker-rt: ""
