apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: nf-conntrack-max
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Test change sysctl net.netfilter.nf_conntrack_max
      include=openshift-control-plane

      [sysctl]
      net.netfilter.nf_conntrack_max=1048578
    name: nfconntrackmax

  recommend:
  - match:
    - label: tuned.openshift.io/elasticsearch
      type: pod
    priority: 5
    profile: nfconntrackmax
